[meta]
name = "Strenda Biocatalysis"
description = "This is a code and schema generator for Strenda Biocatalysis."
paths = [
    "specifications/biocatalyst.md",
    "specifications/components.md",
    "specifications/operation_mode.md",
    "specifications/results.md",
    "specifications/sampling.md",
    "specifications/vessels_and_mixing.md",
    "specifications/reaction_conditions.md",
]

[generate]
xml-schema = { out = "schemes/xml/*.xsd", per-spec = true }
json-schema-all = { out = "schemes/json/", per-spec = true }
python-pydantic = { out = "python/strendabiocat/*.py", per-spec = true }
mk-docs = { out = "docs/guidelines/*.md", per-spec = true }
typescript = { out = "typescript/src/*.ts", per-spec = true }
